// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPH8q2h11HrsSeblO1AzO-vsTbUlQcWA',
    appId: '1:342747374939:android:65cc8e0e192aa7ac04e67e',
    messagingSenderId: '342747374939',
    projectId: 'lingualift-796e0',
    storageBucket: 'lingualift-796e0.firebasestorage.app'
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDuq0ZvTq4o4HGfplemLUvSTwi-6gGb4',
    appId: '1:342747374939:ios:89139efa254d2d0804e67e',
    messagingSenderId: '342747374939',
    projectId: 'lingualift-796e0',
    storageBucket: 'lingualift-796e0.firebasestorage.app'
  );
}

class RmrFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPH8q2h11HrsSeblO1AzO-vsTbUlQcWA',
    appId: '1:342747374939:android:65cc8e0e192aa7ac04e67e',
    messagingSenderId: '342747374939',
    projectId: 'lingualift-796e0',
    storageBucket: 'lingualift-796e0.firebasestorage.app'
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPH8q2h11HrsSeblO1AzO-vsTbUlQcWA',
    appId: '1:342747374939:android:65cc8e0e192aa7ac04e67e',
    messagingSenderId: '342747374939',
    projectId: 'lingualift-796e0',
    storageBucket: 'lingualift-796e0.firebasestorage.app'
  );
}
